Lobook/Lobook/other/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Lobook/Lobook/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    #path('', views.index, name='index'),
    #path('list/',list.site.urls),
    #path('register/',register.site.urls)
]

Lobook/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('list', views.list, name='list'),
    path('login', views.login, name='login'),
    path('newlogin', views.newlogin, name='newlogin'),
    path('update', views.update, name='update'),
    path('lend', views.lend, name='lend'),
    path('delete', views.delete, name='delete'),
    path('edit', views.edit, name='edit'),
    path('signOut',views.signOut,name='signOut'),
]

Lobook/myapp/models.py
from django.db import models
from django.utils import timezone
# bookid: int
# title:タイトル　char
# auther:著者名 char
# updatedAt:更新日時 date
# createdAt:作成日時 date
# purchaseDate:購入日 date
# deadline:貸し出し期限 date
# isAvailable:貸し出し状態 bool


class Book(models.Model):   
    bookid = models.AutoField('本番号',primary_key=True)
    title = models.CharField('タイトル',max_length=100)
    author = models.CharField('著者',max_length=30)
    updatedAt = models.DateTimeField('更新日時',auto_now_add=True)
    createdAt = models.DateTimeField('作成日',auto_now_add=True)
    purchaseDate = models.CharField('購入日' ,max_length=30)
    deadline = models.DateField('貸出期限',auto_now_add=True)
    producedby = models.CharField('出版社',max_length=30)
    isAvailable = models.BooleanField('貸出可否')

    def all(self):
        return self

class Login(models.Model):   
    id = models.IntegerField('id',primary_key=True)
    Loginid = models.CharField('ログインID',max_length=10)
    password = models.CharField('パスワード',max_length=10)
    mail = models.CharField('メールアドレス',max_length=30)
    def __str__(self):
        return self.Loginid

Lobook/myapp/forms.py
from django import forms
from .models import Book
from .models import Login

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title','author','producedby','purchaseDate','isAvailable']
        widgets = {
            'purchaseDate': forms.SelectDateWidget
        }
        #'purchaseDate'

class newLoginForm(forms.ModelForm):
    class Meta:
        model = Login
        fields = ['Loginid','password','mail']

class LoginForm(forms.ModelForm):
    class Meta:
        model = Login
        fields = ['Loginid','password']

Lobook/myapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils import timezone
from .forms import BookForm
from .forms import LoginForm
from .forms import newLoginForm
from .models import Book
from .models import Login
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
from django.db.models import Q
from django.contrib import messages


# Create your views here.
loginName = "ゲスト"

def index(request):
    n = name()
    params = {
        'form': LoginForm(),
        'data': Login.objects.all(),
        'name':n
    }
    if n == "ゲスト":
        return render(request, 'myapp/login.html', params)
    else:
        print(n)
        return render(request, 'myapp/index.html', params)
    

def name():
    global loginName
    if loginName == "ゲスト":
        return "ゲスト"
    else:
        return loginName

def signIn(name):
    if name == "ゲスト":
        return redirect(to='/login')
    else:
        print(name)
        return

def signOut(request):
    global loginName
    loginName = "ゲスト"
    return redirect(to='/')

def login(request):
    global loginName
    if request.method == 'POST':
        _id = request.POST.get('Loginid')
        p = request.POST.get('password')
        l = Login.objects.get(Loginid=_id,password=p)
        print(l,p)
        if l.password == p:
            loginName = _id
            return redirect(to='/')
        else:
            message = "パスワード、またはログインIDが異なります"
            return render(request, 'myapp/login.html', message)
    params = {
        'form': LoginForm(),
        'data': Login.objects.all()
    }
    return render(request, 'myapp/login.html', params)

def newlogin(request):
    params = {
        'form': newLoginForm(),
    }
    if request.method == 'POST':
        l = Login()
        #l.id = 1
        # l.Loginid = request.POST.get('Loginid')
        # l.password = request.POST.get('password')
        # l.mail = request.POST.get('mail')
        log = newLoginForm(request.POST,instance=l)
        if log.is_valid():
            log.save()
        else:
            print('ERROR FROM INVALID')
        return redirect(to='/')
    return render(request, 'myapp/login_new.html', params)

def lend(request):
    n = name()
    today = datetime.today()
    if request.method == 'POST':
        bookid = request.POST.get('hidden')
        print(bookid)
        isAv = request.POST.get('isAvailable')
        if isAv == "True":
            print("a")
            Book.objects.filter(bookid=bookid).update(isAvailable = False,deadline = today + relativedelta(months=1))
        else:
            print(isAv)
            Book.objects.filter(bookid=bookid).update(isAvailable = True,deadline = today + relativedelta(months=1))
        return redirect(to='/lend')

    q_word = request.GET.get('query')
    if q_word:
        data = Book.objects.filter(Q(title__icontains=q_word) | Q(author__icontains=q_word))
    else:
        data = Book.objects.all()
    params = {
        'data': data,
        'name':n
    }
    return render(request, 'myapp/lend.html', params)

def update(request):
    n = name()
    signIn(n)
    if request.method == 'POST':
        q = request.POST.get('hidden')
        i = int(q)
        data = Book.objects.filter(bookid=i)
        params = {
            'data': data,
            'form': BookForm(),
            'name':n
        }
        return render(request, 'myapp/update.html', params)
    return render(request, 'myapp/update.html', {})

def edit(request):
    today = datetime.today()
    bookid = request.POST.get('hidden')
    Book.objects.filter(bookid=bookid).update(
        updatedAt = timezone.now(),
        deadline =  today + relativedelta(months=1),
        isAvailable = True,
        title = request.POST.get('title'),
        author = request.POST.get('author'),
        producedby = request.POST.get('producedby'),
    )
    return redirect(to='/list')
    
def delete(request):
    n = name()
    signIn(n)
    if request.method == 'POST':
        q = request.POST.get('hidden')
        Book.objects.filter(bookid=q).delete()
        return redirect(to='/list')
    params = {
        'name':n
    }
    return render(request, 'myapp/index.html', params)

def register(request):
    n = name()
    signIn(n)
    if request.method == 'POST':
        b = Book()
        b.bookid = len(Book.objects.order_by('-bookid'))+1
        b.createdAt = timezone.now()
        b.updatedAt = timezone.now()
        b.deadline = datetime.today() + relativedelta(months=1)
        b.isAvailable = True
        b.producedby = "不明"
        # b.purchaseDate = timezone.now()
        book = BookForm(request.POST,instance=b)
        if book.is_valid():
            book.save()
        else:
            print('ERROR FROM INVALID')
        return redirect(to='/')
    params = {
        'form': BookForm(),
        'name':n
    }
    return render(request, 'myapp/register/register.html', params)

def list(request):
    n = name()
    signIn(n)
    q_word = request.GET.get('query')
    if q_word:
        data = Book.objects.filter(Q(title__icontains=q_word) | Q(author__icontains=q_word))
    else:
        data = Book.objects.all()
    params = {
        'data': data,
        'name':n
    }
    return render(request, 'myapp/list.html', params)

    

Lobook/myapp/templates/myapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<title>LoBook</title>
</head>
<body>
    <div class="login">
        {% if name == "ゲスト" %}
        <p>こんにちは、{{name}}さん</p><a href="/login"><p>ログイン</p></a>
        {% else%}
        <p>こんにちは、{{name}}さん</p><a href="/signOut"><p>ログアウト</p></a>
        {% endif %}
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <div class="c">
            <div class="contents">
                <a href="/lend"></a>
                <div class="text">本を借りる・レビューする</div>
            </div>
            <div class="contents">
                <a href="/register"></a>
                <div class="text">本を登録する</div>
            </div>
            <div class="contents">
                <a href="/list"></a>
                <div class="text">本を更新する</div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>

Lobook/myapp/templates/myapp/lend.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />

<title>LoBook</title>
</head>
<body>
    <div class="login">
        {% if name == "ゲスト" %}
        <p>こんにちは、{{name}}さん</p><a href="/login"><p>ログイン</p></a>
        {% else%}
        <p>こんにちは、{{name}}さん</p><a href="/signOut"><p>ログアウト</p></a>
        {% endif %}
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <h2>一覧ページ</h2>
    </div>
    <form action="" method="get" class="query">
        <input name="query" value="{{ request.GET.query }}" type="text">
        <button class="button" type="submit">検索する</button>
    </form>
    <table border="1" id="list">
        <tr>
            <th>id</th>
            <th>タイトル</th>
            <th>著者</th>
            <th>出版社</th>
            <th>購入日</th>
            <th>貸出期限</th>
            <th>貸出可能</th>
            <th>本のレビュー</th>
            <th>操作</th>
        </tr>
        {% for d in data %}
        {% if d.isAvailable is True %}
        <tr>
        {% else %}
        <tr class="nonaval">
        {% endif %}
            <td id="bookid" value="{{ d.bookid }}">{{ d.bookid }}</td>
            <td>{{ d.title }}</td>
            <td>{{ d.author }}</td>
            <td>{{ d.producedby }}</td>
            <td>{{ d.purchaseDate }}</td>
            <td>{{ d.deadline }}</td>
            {% if d.isAvailable is True %}
            <td>可能</td>
            {% else %}
            <td>不可</td>
            {% endif %}
            <td><a class="review" href="/">レビューページ</a></td>            
            <td>
                <form action="/lend" method="POST" class="u">
                    {% csrf_token %}
                    <input type="hidden" name="hidden" value="{{ d.bookid }}">
                    <input type="hidden" name="isAvailable" value="{{ d.isAvailable }}">
                    {% if d.isAvailable is True %}
                    <input class="button" type="submit" value="借りる" name="l">
                    {% else %}
                    <input class="button" type="submit" value="返却する" name="r">
                    {% endif %}
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>

Lobook/myapp/templates/myapp/list.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<title>LoBook</title>
</head>
<body>
    <div class="login">
        {% if name == "ゲスト" %}
        <p>こんにちは、{{name}}さん</p><a href="/login"><p>ログイン</p></a>
        {% else%}
        <p>こんにちは、{{name}}さん</p><a href="/signOut"><p>ログアウト</p></a>
        {% endif %}
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <h2>一覧ページ</h2>
    </div>
    <form action="" method="get" class="query">
        <input name="query" value="{{ request.GET.query }}" type="text">
        <button class="button" type="submit">検索する</button>
    </form>
    <table border="1" id="list">
        <tr>
            <th>id</th>
            <th>タイトル</th>
            <th>著者</th>
            <th>出版社</th>
            <th>購入日</th>
            <th>貸出期限</th>
            <th>貸出可能</th>
            <th>更新日時</th>
            <th>作成日</th>
            <th>操作</th>
        </tr>
        {% for d in data %}
        {% if d.isAvailable is True %}
        <tr>
        {% else %}
        <tr class="nonaval">
        {% endif %}
            <td id="bookid" value="{{ d.bookid }}">{{ d.bookid }}</td>
            <td>{{ d.title }}</td>
            <td>{{ d.author }}</td>
            <td>{{ d.producedby }}</td>
            <td>{{ d.purchaseDate }}</td>
            <td>{{ d.deadline }}</td>
            {% if d.isAvailable is True %}
            <td>可能</td>
            {% else %}
            <td>不可</td>
            {% endif %}
            <td>{{ d.updatedAt }}</td>
            <td>{{ d.createdAt }}</td>
            <td>
                <form action="/update" method="POST" class="u">
                    {% csrf_token %}
                    <input type="hidden" name="hidden" value="{{ d.bookid }}">
                    <input class="button" type="submit" value="更新" name="更新">
                </form>
                <form action="/delete" method="POST" class="u">
                    {% csrf_token %}
                    <input type="hidden" name="hidden" value="{{ d.bookid }}">
                    <input class="remove" type="submit" value="削除"　name="delete">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>

Lobook/myapp/templates/myapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<title>LoBook</title>
</head>
<body>
    <div class="login">
        <p>ログイン</p>
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <h2>ログインページ</h2>
    </div>
    <table class="form_table" style="margin: 40px auto; padding: 10px; font-size: 20px;">
        <form action="{% url 'login' %}" method="post">
            {{ form.as_table }}
            {% csrf_token %}
            <tr><td></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
    <h2 style="margin: 40px;"><a href="/newlogin">新規登録</a></h2>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>

Lobook/myapp/templates/myapp/login_new.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<title>LoBook</title>
</head>
<body>
    <div class="login">
        <p>ログイン</p>
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <h2>新規登録</h2>
    </div>
    <table class="form_table" style="margin: 40px auto; padding: 10px; font-size: 20px;">
        <form action="{% url 'newlogin' %}" method="post">
            {{ form.as_table }}
            {% csrf_token %}
            <tr><td></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>

Lobook/myapp/templates/myapp/register/register.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<title>LoBook</title>
</head>
<body>
    <div class="login">
        {% if name == "ゲスト" %}
        <p>こんにちは、{{name}}さん</p><a href="/login"><p>ログイン</p></a>
        {% else%}
        <p>こんにちは、{{name}}さん</p><a href="/signOut"><p>ログアウト</p></a>
        {% endif %}
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <h2>本の登録ページ</h2>
    </div>
    <div class="form_book">
    <p>入力フォーム</p>
    <table class="form_table" style="margin: 0 auto;">
        <form action="{% url 'register' %}" method="post">
            {{ form.as_table }}
            {% csrf_token %}
            <tr><td></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
    </div>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>

Lobook/myapp/templates/myapp/update.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<title>LoBook</title>
</head>
<body>
    <div class="login">
        {% if name == "ゲスト" %}
        <p>こんにちは、{{name}}さん</p><a href="/login"><p>ログイン</p></a>
        {% else%}
        <p>こんにちは、{{name}}さん</p><a href="/signOut"><p>ログアウト</p></a>
        {% endif %}
    </div>
    <div class="pastel">
        <h1><a href="/">L♡Book</a></h1>
        <h2>本を大切に管理するシステム</h2>
        <h2>本の登録ページ</h2>
    </div>
    <div class="form_book">
    <p>入力フォーム</p>
    <table class="form_table" style="margin: 0 auto;">
        <form action="{% url 'edit' %}" method="post">
            {% for d in data %}
            <tbody>
                <input type="hidden" name="hidden" value="{{ d.bookid }}">
                <tr>
                    <th><label for="id_title">タイトル:</label></th>
                    <td><input type="text" name="title" maxlength="100" required="" id="id_title" value="{{d.title}}"></td>
                </tr>
                <tr>
                    <th><label for="id_author">著者:</label></th>
                    <td><input type="text" name="author" maxlength="30" required="" id="id_author" value="{{d.author}}"></td>
                </tr>
                <tr>
                    <th><label for="id_producedby">出版社:</label></th>
                    <td><input type="text" name="producedby" maxlength="30" required="" id="id_producedby" value="{{d.producedby}}"></td>
                </tr>
            </tbody>
            {% endfor %}
            {% csrf_token %}
            <tr><td></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
    </div>
    <footer class="footer">
        <small>© 2020 ishida yutaka.</small>
    </footer>
</body>
</html>